# Generated by Django 4.1.7 on 2023-03-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0003_acessorio_cor_veiculo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculo",
            name="preco",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
