# Generated by Django 4.1.7 on 2023-03-30 23:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0004_alter_veiculo_preco"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cor",
            options={"verbose_name_plural": "Cores"},
        ),
    ]
