# Generated by Django 4.1.7 on 2023-03-30 23:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0005_alter_cor_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="veiculo",
            old_name="nome",
            new_name="modelo",
        ),
    ]
