# Generated by Django 4.1.7 on 2023-05-05 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0006_rename_nome_veiculo_modelo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="garagem.categoria",
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="garagem.marca"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="modelo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="garagem.modelo"
            ),
        ),
    ]
