# Generated by Django 4.1.7 on 2023-05-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0007_modelo_alter_veiculo_modelo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculo",
            name="modelo",
            field=models.CharField(max_length=50),
        ),
    ]
